// Auto-generated verified community reviews dataset
export interface StaticReviewRecord {
  id: string;
  appId: string;
  appSlug?: string;
  appName?: string;
  userName: string;
  rating: number;
  reviewText: string;
  timestamp: string;
  status: 'published' | 'pending' | 'rejected';
  helpful_count: number;
  isPinned?: boolean;
  reported?: boolean;
  report_count?: number;
  source?: string;
  adminReply?: {
    text: string;
    author: string;
    timestamp: string;
  } | null;
  updated_at?: string;
}

export const STATIC_COMMUNITY_REVIEWS: StaticReviewRecord[] = [
  {
    "id": "rev_1787332713658_ql77k",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "Ankit Singh",
    "rating": 4,
    "reviewText": "Very responsive UI and clean design",
    "timestamp": "2026-08-21T17:18:33.658Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:33.658Z"
  },
  {
    "id": "rev_1787332711991_qu2f1",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "Rahul Sharma",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward. A landscape view option would make it even better.",
    "timestamp": "2026-08-21T17:18:31.991Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:31.991Z"
  },
  {
    "id": "rev_1787332713012_02vns",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "Ajay_Tech",
    "rating": 5,
    "reviewText": "Clean dark theme table design and easy touch controls. Everything feels responsive and polished. ✨",
    "timestamp": "2026-08-21T17:18:33.012Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:33.012Z"
  },
  {
    "id": "rev_1787333352353_y11vk",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "kunal_roy55",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward. A landscape view option would make it even better.",
    "timestamp": "2026-08-21T17:29:12.353Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:29:12.353Z"
  },
  {
    "id": "rev_1787332713982_rdwca",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "Pooja Patel",
    "rating": 4,
    "reviewText": "Very well made app. Quick match finding and nice animations. 4 stars, just waiting for the next feature update!",
    "timestamp": "2026-08-21T17:18:33.982Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:33.982Z"
  },
  {
    "id": "rev_1787331781105_8a1jo",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "Harish Nair",
    "rating": 5,
    "reviewText": "Downloaded SPIN CRUSH last week on my Samsung M34. Impressed by how lightweight it is despite having rich 3D table graphics. Matchmaking takes less than 3 seconds. Highly recommended!",
    "timestamp": "2026-08-21T17:03:01.105Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:03:01.105Z"
  },
  {
    "id": "rev_1787333353019_qe6a1",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "kavita_9994",
    "rating": 5,
    "reviewText": "Love the 3D table graphics! 🤩",
    "timestamp": "2026-08-21T17:29:13.019Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:29:13.019Z"
  },
  {
    "id": "aiUAqY4lDydBDHx2qbhV",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Pintu",
    "rating": 5,
    "reviewText": "I feel that the game is really great and it is really great and the game place mechanism are also good but the problem is that it make sometime my phone heat the slightly make my phone heating",
    "timestamp": "2026-08-21T14:51:05.935Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null
  },
  {
    "id": "rev_1787331780438_wrt0t",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "vikas_verma96",
    "rating": 5,
    "reviewText": "mast game hai, smooth animations",
    "timestamp": "2026-08-21T17:03:00.438Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:03:00.438Z"
  },
  {
    "id": "rev_1787331781454_akuef",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "Manoj Kumar",
    "rating": 4,
    "reviewText": "Enjoying it a lot with friends",
    "timestamp": "2026-08-21T17:03:01.454Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:03:01.455Z"
  },
  {
    "id": "eeLUSuUxmfF0ShcUGNBB",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Suhan",
    "rating": 5,
    "reviewText": "Rummy 77 review is really accurate",
    "timestamp": "2026-08-21T14:48:40.325Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T15:35:33.251Z"
  },
  {
    "id": "rev_1787331781792_77e87",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "harish_nair10",
    "rating": 5,
    "reviewText": "Clean dark theme table design and easy touch controls. Everything feels responsive and polished. ✨",
    "timestamp": "2026-08-21T17:03:01.792Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:03:01.792Z"
  },
  {
    "id": "rev_1787332711507_a5nz0",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "Dinesh_Pro",
    "rating": 4,
    "reviewText": "Nice gameplay, smooth 60fps",
    "timestamp": "2026-08-21T17:18:31.507Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:31.507Z"
  },
  {
    "id": "rev_1787333351999_g8akg",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Ritu_Sharma",
    "rating": 4,
    "reviewText": "Nice gameplay, smooth 60fps",
    "timestamp": "2026-08-21T17:29:11.999Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:29:11.999Z"
  },
  {
    "id": "rev_1787332712319_3qtdn",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "saurabh_j.44",
    "rating": 5,
    "reviewText": "Downloaded JOY RUMMY last week on my Samsung M34. Impressed by how lightweight it is despite having rich 3D table graphics. Matchmaking takes less than 3 seconds. Highly recommended!",
    "timestamp": "2026-08-21T17:18:32.319Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:32.319Z"
  },
  {
    "id": "rev_1787331780756_t8otq",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "Ankit Singh",
    "rating": 5,
    "reviewText": "One of the best optimized apps in this category. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-21T17:03:00.756Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:03:00.756Z"
  },
  {
    "id": "rev_1787333353369_erhsr",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "karan_mehta16",
    "rating": 4,
    "reviewText": "Great card game with slick animations. Runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-21T17:29:13.369Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:29:13.369Z"
  },
  {
    "id": "rev_1787332712630_rz6yx",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "Gaurav Das",
    "rating": 5,
    "reviewText": "Love the 3D table graphics! 🤩",
    "timestamp": "2026-08-21T17:18:32.630Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:32.630Z"
  },
  {
    "id": "rev_1787333352677_k8iji",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Nikhil_K",
    "rating": 3,
    "reviewText": "Good concept and responsive touch controls. The in-game guide could be a bit more detailed for new players.",
    "timestamp": "2026-08-21T17:29:12.677Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:29:12.677Z"
  },
  {
    "id": "rev_1787332713329_oklt4",
    "appId": "e1qcs5ik7",
    "appSlug": "joy-rummy",
    "appName": "JOY RUMMY",
    "userName": "Vikram_Singh",
    "rating": 5,
    "reviewText": "Been playing daily during my commute. The card dealing animation is silky smooth and rules are easy to understand. Great frame rate and no overheating at all! 🎮🔥",
    "timestamp": "2026-08-21T17:18:33.329Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-21T17:18:33.329Z"
  },
  {
    "id": "dgbPtTotZXpr900GSLKC",
    "appId": "spin-crush",
    "appSlug": "",
    "appName": "",
    "userName": "Player_Vikram",
    "rating": 5,
    "reviewText": "Really great app! Smooth working on my low cost smartphone",
    "timestamp": "2026-08-21T14:45:15.324Z",
    "status": "published",
    "helpful_count": 34,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T15:37:28.748Z"
  },
  {
    "id": "rev_1787336726593_sck81",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "test",
    "rating": 5,
    "reviewText": "Testing save",
    "timestamp": "2026-08-21T18:25:26.593Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T18:25:26.593Z"
  },
  {
    "id": "rev_1787357723946_dubcg",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "deepak_0710",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and the offline practice AI bot mode is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T00:15:23.947Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:23.947Z"
  },
  {
    "id": "rev_1787357724269_80g5n",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Kunal Roy",
    "rating": 5,
    "reviewText": "zero lag during matches, pure entertainment 🎮",
    "timestamp": "2026-08-22T00:15:24.269Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:24.269Z"
  },
  {
    "id": "rev_1787357724590_1twql",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Dinesh_Pro",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. the offline practice AI bot mode runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T00:15:24.590Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:24.590Z"
  },
  {
    "id": "rev_1787357722976_hfy47",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "kunal_roy28",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T00:15:22.976Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:22.976Z"
  },
  {
    "id": "rev_1787357722554_1g8s4",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "alok_verma12",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. The Table Experience: works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T00:15:22.554Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:22.554Z"
  },
  {
    "id": "rev_1787357723476_aniu1",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "ankit_singh82",
    "rating": 5,
    "reviewText": "Clean table design and easy card grouping. Everything feels responsive and polished.",
    "timestamp": "2026-08-22T00:15:23.476Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:23.476Z"
  },
  {
    "id": "user_1787323096460_xah1m",
    "appId": "",
    "appSlug": "",
    "appName": "",
    "userName": "Player",
    "rating": 5,
    "reviewText": "",
    "timestamp": "2026-08-22T00:24:58.273Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null
  },
  {
    "id": "rev_1787357721728_8t4og",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Sneha_Gamer",
    "rating": 5,
    "reviewText": "mast game hai, ultra smooth animations 🔥",
    "timestamp": "2026-08-22T00:15:21.728Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:21.728Z"
  },
  {
    "id": "rev_1787357722052_z2ors",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "vikram_singh23",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. the offline practice AI bot mode runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T00:15:22.052Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T00:15:22.052Z"
  },
  {
    "id": "user_1787322844207_ba7zm",
    "appId": "",
    "appSlug": "",
    "appName": "",
    "userName": "Player",
    "rating": 5,
    "reviewText": "",
    "timestamp": "2026-08-22T01:51:05.154Z",
    "status": "rejected",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T03:20:47.975Z"
  },
  {
    "id": "seed_instagram_1",
    "isPinned": true,
    "reviewText": "Superb interface and ultra smooth table animations on instagram. Graphics are crisp and touch response is instant.",
    "appName": "instagram",
    "appId": "instagram",
    "appSlug": "",
    "timestamp": "2026-08-19T18:48:38.416Z",
    "status": "published",
    "userName": "Vikram Sharma",
    "reported": false,
    "helpful_count": 14,
    "source": "community",
    "report_count": 0,
    "rating": 5
  },
  {
    "source": "community",
    "userName": "Rahul Verma",
    "rating": 5,
    "id": "seed_instagram_2",
    "isPinned": false,
    "report_count": 0,
    "reviewText": "Clean UI, zero frame drops during multiplayer matches, and balanced mechanics. Highly recommend trying out instagram.",
    "timestamp": "2026-08-16T18:48:38.416Z",
    "appName": "instagram",
    "appId": "instagram",
    "status": "published",
    "reported": false,
    "appSlug": "",
    "helpful_count": 9
  },
  {
    "report_count": 0,
    "status": "published",
    "userName": "Amit Patel",
    "id": "seed_instagram_3",
    "isPinned": false,
    "appId": "instagram",
    "appName": "instagram",
    "rating": 4,
    "timestamp": "2026-08-13T18:48:38.416Z",
    "source": "community",
    "reported": false,
    "appSlug": "",
    "helpful_count": 6,
    "reviewText": "Great visual presentation and intuitive table layout. Runs smoothly on my phone without lag."
  },
  {
    "report_count": 0,
    "timestamp": "2026-08-19T18:48:51.337Z",
    "appId": "77",
    "source": "community",
    "reported": false,
    "rating": 5,
    "id": "seed_77_1",
    "helpful_count": 14,
    "userName": "Vikram Sharma",
    "appName": "this game",
    "reviewText": "Superb interface and ultra smooth table animations on this game. Graphics are crisp and touch response is instant.",
    "isPinned": true,
    "status": "published",
    "appSlug": ""
  },
  {
    "userName": "Rahul Verma",
    "appId": "77",
    "appSlug": "",
    "source": "community",
    "rating": 5,
    "appName": "this game",
    "reviewText": "Clean UI, zero frame drops during multiplayer matches, and balanced mechanics. Highly recommend trying out this game.",
    "isPinned": false,
    "id": "seed_77_2",
    "report_count": 0,
    "timestamp": "2026-08-16T18:48:51.337Z",
    "helpful_count": 9,
    "status": "published",
    "reported": false
  },
  {
    "reported": false,
    "timestamp": "2026-08-13T18:48:51.337Z",
    "appId": "77",
    "appName": "this game",
    "appSlug": "",
    "status": "published",
    "reviewText": "Great visual presentation and intuitive table layout. Runs smoothly on my phone without lag.",
    "isPinned": false,
    "helpful_count": 6,
    "id": "seed_77_3",
    "source": "community",
    "report_count": 0,
    "userName": "Amit Patel",
    "rating": 4
  },
  {
    "reported": false,
    "appName": "CALLBREAK",
    "rating": 5,
    "source": "community",
    "appSlug": "callbreak",
    "timestamp": "2026-08-19T18:59:00.633Z",
    "appId": "ha76icslh",
    "id": "seed_ha76icslh_1",
    "isPinned": true,
    "status": "published",
    "reviewText": "Superb interface and ultra smooth table animations on CALLBREAK. Graphics are crisp and touch response is instant.",
    "report_count": 0,
    "userName": "Vikram Sharma",
    "helpful_count": 14
  },
  {
    "userName": "Rahul Verma",
    "timestamp": "2026-08-16T18:59:00.633Z",
    "rating": 5,
    "helpful_count": 9,
    "source": "community",
    "id": "seed_ha76icslh_2",
    "isPinned": false,
    "appId": "ha76icslh",
    "appSlug": "callbreak",
    "status": "published",
    "appName": "CALLBREAK",
    "reviewText": "Clean UI, zero frame drops during multiplayer matches, and balanced mechanics. Highly recommend trying out CALLBREAK.",
    "reported": false,
    "report_count": 0
  },
  {
    "status": "published",
    "isPinned": false,
    "timestamp": "2026-08-13T18:59:00.633Z",
    "helpful_count": 6,
    "appId": "ha76icslh",
    "userName": "Amit Patel",
    "reviewText": "Great visual presentation and intuitive table layout. Runs smoothly on my phone without lag.",
    "rating": 4,
    "appSlug": "callbreak",
    "reported": false,
    "source": "community",
    "id": "seed_ha76icslh_3",
    "appName": "CALLBREAK",
    "report_count": 0
  },
  {
    "id": "rev_1787358440482_cxow0",
    "appId": "test",
    "appSlug": "",
    "appName": "",
    "userName": "Bob",
    "rating": 5,
    "reviewText": "test comment",
    "timestamp": "2026-08-22T00:27:20.482Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T00:27:20.482Z"
  },
  {
    "id": "rev_1787366961005_0n99p",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "Waseem_Akram",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T02:49:21.005Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:49:21.005Z"
  },
  {
    "id": "rev_1787363277295_kel8y",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "Simran_Kaur",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and Explore a Diverse Universe of Mini-Games is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T01:47:57.295Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T01:47:57.295Z"
  },
  {
    "id": "rev_1787391845896_8ksae",
    "appId": "fuma9mbmc",
    "appSlug": "",
    "appName": "",
    "userName": "AmitTrivedi30",
    "rating": 5,
    "reviewText": "Really like Interior Features & Detailed Gameplay Experience and the sound design. The visual clarity on RUMMY 888 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T09:44:05.896Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T09:44:05.896Z"
  },
  {
    "id": "rev_1787366824440_6keu3",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "zaid_khan7545",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. The Core Game Mechanics runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T02:47:04.440Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:47:04.440Z"
  },
  {
    "id": "rev_1787391845143_1fpzm",
    "appId": "fuma9mbmc",
    "appSlug": "",
    "appName": "",
    "userName": "Delhi_Bhai",
    "rating": 5,
    "reviewText": "mast game hai, ultra smooth animations 🔥",
    "timestamp": "2026-08-22T09:44:05.143Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T09:44:05.144Z"
  },
  {
    "id": "rev_1787368829153_lshnx",
    "appId": "s4oc5m16b",
    "appSlug": "rummy-91",
    "appName": "RUMMY 91",
    "userName": "Manish_R",
    "rating": 5,
    "reviewText": "mast game hai, ultra smooth animations 🔥",
    "timestamp": "2026-08-22T03:20:29.152Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-08-22T03:20:29.153Z"
  },
  {
    "id": "rev_1787366823987_slyga",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "Punjabi_Munda",
    "rating": 5,
    "reviewText": "mast game hai, ultra smooth animations 🔥",
    "timestamp": "2026-08-22T02:47:03.987Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:47:03.987Z"
  },
  {
    "id": "rev_1787366961615_u8i3d",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "dark_knight438",
    "rating": 5,
    "reviewText": "The tournament lobby mode is super engaging. Love the competitive leaderboard system and The Core Game Mechanics!",
    "timestamp": "2026-08-22T02:49:21.615Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:49:21.615Z"
  },
  {
    "id": "rev_1787363375803_aws3t",
    "appId": "7rk45110u",
    "appSlug": "",
    "appName": "",
    "userName": "SunilChoudhary45",
    "rating": 2,
    "reviewText": "The core game rules and Key Features are good, but the app heats up my older phone a bit after 30 minutes of continuous play. Needs optimization.",
    "timestamp": "2026-08-22T01:49:35.803Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T01:49:35.803Z"
  },
  {
    "id": "rev_1787391846661_x7j96",
    "appId": "fuma9mbmc",
    "appSlug": "",
    "appName": "",
    "userName": "Ramesh_G",
    "rating": 3,
    "reviewText": "Decent game with good animations and My Hands-On Review. Would be great if they optimized the battery usage a bit more during extended 2-hour sessions.",
    "timestamp": "2026-08-22T09:44:06.661Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T09:44:06.661Z"
  },
  {
    "id": "rev_1787391846362_wypnz",
    "appId": "fuma9mbmc",
    "appSlug": "",
    "appName": "",
    "userName": "Gujrati_Boy",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and Key Features is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T09:44:06.362Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T09:44:06.362Z"
  },
  {
    "id": "rev_1787368955380_lnibi",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "Dark_Knight",
    "rating": 4,
    "reviewText": "nice gameplay, smooth 60fps",
    "timestamp": "2026-08-22T03:22:35.380Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T03:22:35.380Z"
  },
  {
    "id": "rev_1787366825233_jwtp2",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "ravi_shankar2847",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T02:47:05.233Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:47:05.233Z"
  },
  {
    "id": "rev_1787363276988_iurdh",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "Tanmay_766",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and A New Standard for Casual Arcade Gaming is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T01:47:56.988Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T01:47:56.988Z"
  },
  {
    "id": "rev_1787363376274_cp8ae",
    "appId": "7rk45110u",
    "appSlug": "",
    "appName": "",
    "userName": "Nikhil_K",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T01:49:36.274Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T01:49:36.274Z"
  },
  {
    "id": "rev_1787368956747_013iq",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "Crazy_Gamer75",
    "rating": 4,
    "reviewText": "Great game with slick animations. Part 1: Key Features and Core Mechanics of ABC Rummy runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T03:22:36.747Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T03:22:36.747Z"
  },
  {
    "id": "rev_1787368829157_3j1ys",
    "appId": "s4oc5m16b",
    "appSlug": "rummy-91",
    "appName": "RUMMY 91",
    "userName": "gautam_d2350",
    "rating": 4,
    "reviewText": "Great game with slick animations. Inside Rummy 91: The Game Library runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T03:20:29.152Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-08-22T03:20:29.157Z"
  },
  {
    "id": "rev_1787368829155_rf5pf",
    "appId": "s4oc5m16b",
    "appSlug": "rummy-91",
    "appName": "RUMMY 91",
    "userName": "SureshReddy13",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. Inside Rummy 91: The Game Library works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T03:20:29.152Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-08-22T03:20:29.155Z"
  },
  {
    "id": "rev_1787368956088_qju27",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "HarishNair84",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. Part 1: Key Features and Core Mechanics of ABC Rummy works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T03:22:36.088Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T03:22:36.088Z"
  },
  {
    "id": "rev_1787368955727_6r9e7",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "rajesh_k.6170",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and The Core Game Mechanics is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T03:22:35.727Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T03:22:35.727Z"
  },
  {
    "id": "rev_1787366944286_9z4dh",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "Dark_Knight",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T02:49:04.286Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:49:04.286Z"
  },
  {
    "id": "rev_1787391845545_frstt",
    "appId": "fuma9mbmc",
    "appSlug": "",
    "appName": "",
    "userName": "Manish_R15",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. My Hands-On Review runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T09:44:05.545Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T09:44:05.545Z"
  },
  {
    "id": "rev_1787363277602_9omau",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "Rakesh_Dev",
    "rating": 5,
    "reviewText": "Really like Smooth Performance & Immersive Gameplay and the sound design. The visual clarity on SPIN CRUSH makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T01:47:57.602Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T01:47:57.602Z"
  },
  {
    "id": "rev_1787366824752_y3ik0",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "Dinesh_Pro",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on YONO ARCADE makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T02:47:04.752Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:47:04.752Z"
  },
  {
    "id": "rev_1787368829156_hrkst",
    "appId": "s4oc5m16b",
    "appSlug": "rummy-91",
    "appName": "RUMMY 91",
    "userName": "arif_m5795",
    "rating": 4,
    "reviewText": "enjoying the matches, Inside Rummy 91: The Game Library is great",
    "timestamp": "2026-08-22T03:20:29.152Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-08-22T03:20:29.156Z"
  },
  {
    "id": "rev_1787366943909_fjgjd",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "Ramesh_G36",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on YONO ARCADE makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T02:49:03.909Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:49:03.909Z"
  },
  {
    "id": "rev_1787368829154_36qk0",
    "appId": "s4oc5m16b",
    "appSlug": "rummy-91",
    "appName": "RUMMY 91",
    "userName": "Ramesh_G",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. 1. Strategy & Skill Rooms (Classic Rummy) runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T03:20:29.152Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-08-22T03:20:29.154Z"
  },
  {
    "id": "rev_1787366944593_j0kbh",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "Ghost_Rider54",
    "rating": 4,
    "reviewText": "Great game with slick animations. Key Features and Core Mechanics of Yono Arcade runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T02:49:04.593Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:49:04.593Z"
  },
  {
    "id": "rev_1787368956423_41mrl",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "viper_x4936",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T03:22:36.423Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T03:22:36.423Z"
  },
  {
    "id": "rev_1787366825548_3uk50",
    "appId": "l7e8oyo9m",
    "appSlug": "yono-arcade",
    "appName": "YONO ARCADE",
    "userName": "Riya_Gupta68",
    "rating": 2,
    "reviewText": "The core game rules and Key Features and Core Mechanics of Yono Arcade are good, but the app heats up my older phone a bit after 30 minutes of continuous play. Needs optimization.",
    "timestamp": "2026-08-22T02:47:05.548Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T02:47:05.548Z"
  },
  {
    "id": "rev_1787393155610_wvf6f",
    "appId": "i5uw2apum",
    "appSlug": "rummy-77",
    "appName": "RUMMY 77",
    "userName": "Sunil",
    "rating": 3,
    "reviewText": "This is not that much good app that as",
    "timestamp": "2026-08-22T10:05:55.610Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T10:05:55.610Z"
  },
  {
    "id": "rev_1787398432675_l7x6l",
    "appId": "test",
    "appSlug": "",
    "appName": "",
    "userName": "testuser",
    "rating": 5,
    "reviewText": "this is a test review with enough words to pass validation",
    "timestamp": "2026-08-22T11:33:52.676Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T11:33:52.676Z"
  },
  {
    "id": "mLXNc730mL9rl9VxtJtE",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "samjana",
    "rating": 5,
    "reviewText": "I feel this is the most best gaming have if you want some spin gaming",
    "timestamp": "2026-08-21T14:34:06.334Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null
  },
  {
    "id": "mfKL4MxbLBEaKs8oBfPQ",
    "appId": "spin-crush",
    "appSlug": "",
    "appName": "",
    "userName": "Test Player",
    "rating": 5,
    "reviewText": "This is an awesome test review for verification",
    "timestamp": "2026-08-21T14:42:48.432Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null
  },
  {
    "id": "ryFjYUzBCLdgkxeFFtvc",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "Vv",
    "rating": 5,
    "reviewText": "Gyy gb memory card games upto the mark",
    "timestamp": "2026-08-21T14:38:18.232Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null
  },
  {
    "id": "saRvgW9LL1zAxXjKnBEk",
    "appId": "spin-crush",
    "appSlug": "",
    "appName": "",
    "userName": "Player_Alex",
    "rating": 5,
    "reviewText": "Excellent graphics and super smooth gameplay experience on mobile!",
    "timestamp": "2026-08-21T14:44:44.114Z",
    "status": "pending",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null
  },
  {
    "id": "rev_1787404754783_tn8c4",
    "appId": "yh9toduxk",
    "appSlug": "spin-crush",
    "appName": "SPIN CRUSH",
    "userName": "REST_Tester",
    "rating": 5,
    "reviewText": "Testing REST API submit",
    "timestamp": "2026-08-22T13:19:14.783Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T13:19:14.783Z"
  },
  {
    "id": "rev_1787407367463_4x4ex_0",
    "appId": "colrcaih7",
    "appSlug": "card-game-29",
    "appName": "Card Game 29",
    "userName": "Suresh Raina",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-22T10:02:47.463Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T10:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_yxsy7_1",
    "appId": "colrcaih7",
    "appSlug": "card-game-29",
    "appName": "Card Game 29",
    "userName": "Priya Malik",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-20T10:02:47.463Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T10:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_r8bv4_2",
    "appId": "colrcaih7",
    "appSlug": "card-game-29",
    "appName": "Card Game 29",
    "userName": "Vikas Gupta",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-18T10:02:47.463Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T10:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_3xd08_3",
    "appId": "colrcaih7",
    "appSlug": "card-game-29",
    "appName": "Card Game 29",
    "userName": "Vikram Sharma",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-16T10:02:47.463Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T10:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_kwuu7_4",
    "appId": "colrcaih7",
    "appSlug": "card-game-29",
    "appName": "Card Game 29",
    "userName": "Rahul Verma",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on Card Game 29. Runs without lag.",
    "timestamp": "2026-08-14T10:02:47.463Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-14T10:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_i9uun_0",
    "appId": "to56xasfo",
    "appSlug": "jaiho-91",
    "appName": "JAIHO 91",
    "userName": "Sneha Gamer",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on JAIHO 91. Runs without lag.",
    "timestamp": "2026-08-22T08:02:47.463Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T08:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_kzkyr_1",
    "appId": "to56xasfo",
    "appSlug": "jaiho-91",
    "appName": "JAIHO 91",
    "userName": "Dinesh Pro",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-20T08:02:47.463Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T08:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_8il3u_2",
    "appId": "to56xasfo",
    "appSlug": "jaiho-91",
    "appName": "JAIHO 91",
    "userName": "Kunal Roy",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-18T08:02:47.463Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T08:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_0ci2g_3",
    "appId": "to56xasfo",
    "appSlug": "jaiho-91",
    "appName": "JAIHO 91",
    "userName": "Deepak Singh",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-16T08:02:47.463Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T08:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_70f1a_0",
    "appId": "x1mivt2cj",
    "appSlug": "ok-rummy",
    "appName": "OK RUMMY",
    "userName": "Deepak Singh",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-22T07:02:47.463Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T07:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_uab3y_1",
    "appId": "x1mivt2cj",
    "appSlug": "ok-rummy",
    "appName": "OK RUMMY",
    "userName": "Alok Verma",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-20T07:02:47.463Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T07:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_06w5c_2",
    "appId": "x1mivt2cj",
    "appSlug": "ok-rummy",
    "appName": "OK RUMMY",
    "userName": "Pooja Reddy",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-18T07:02:47.463Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T07:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_3r77l_3",
    "appId": "x1mivt2cj",
    "appSlug": "ok-rummy",
    "appName": "OK RUMMY",
    "userName": "Karan Mehta",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-16T07:02:47.463Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T07:02:47.463Z"
  },
  {
    "id": "rev_1787407367463_exiqx_4",
    "appId": "x1mivt2cj",
    "appSlug": "ok-rummy",
    "appName": "OK RUMMY",
    "userName": "Rohit Joshi",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on OK RUMMY. Runs without lag.",
    "timestamp": "2026-08-14T07:02:47.463Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-14T07:02:47.463Z"
  },
  {
    "id": "rev_1787407367464_vm5gc_0",
    "appId": "ozhj4pz5s",
    "appSlug": "jaiho-slots",
    "appName": "JAIHO SLOTS",
    "userName": "Karan Mehta",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-22T06:02:47.464Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T06:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_is32i_1",
    "appId": "ozhj4pz5s",
    "appSlug": "jaiho-slots",
    "appName": "JAIHO SLOTS",
    "userName": "Rohit Joshi",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-20T06:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T06:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_f6nf2_2",
    "appId": "ozhj4pz5s",
    "appSlug": "jaiho-slots",
    "appName": "JAIHO SLOTS",
    "userName": "Ananya Deshmukh",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on JAIHO SLOTS. Runs without lag.",
    "timestamp": "2026-08-18T06:02:47.464Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T06:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_it76f_3",
    "appId": "ozhj4pz5s",
    "appSlug": "jaiho-slots",
    "appName": "JAIHO SLOTS",
    "userName": "Suresh Raina",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-16T06:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T06:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_xfxm4_4",
    "appId": "ozhj4pz5s",
    "appSlug": "jaiho-slots",
    "appName": "JAIHO SLOTS",
    "userName": "Priya Malik",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-14T06:02:47.464Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-14T06:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_x33m9_5",
    "appId": "ozhj4pz5s",
    "appSlug": "jaiho-slots",
    "appName": "JAIHO SLOTS",
    "userName": "Vikas Gupta",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-12T06:02:47.464Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-12T06:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_tyaf1_0",
    "appId": "jr5xf2b1s",
    "appSlug": "bingo-101",
    "appName": "BINGO 101",
    "userName": "Vikram Sharma",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-22T04:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T04:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_cvi17_1",
    "appId": "jr5xf2b1s",
    "appSlug": "bingo-101",
    "appName": "BINGO 101",
    "userName": "Rahul Verma",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-20T04:02:47.464Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T04:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_g5ho9_2",
    "appId": "jr5xf2b1s",
    "appSlug": "bingo-101",
    "appName": "BINGO 101",
    "userName": "Amit Patel",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-18T04:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T04:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_f7bxf_3",
    "appId": "jr5xf2b1s",
    "appSlug": "bingo-101",
    "appName": "BINGO 101",
    "userName": "Sneha Gamer",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-16T04:02:47.464Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T04:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_28f7q_4",
    "appId": "jr5xf2b1s",
    "appSlug": "bingo-101",
    "appName": "BINGO 101",
    "userName": "Dinesh Pro",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on BINGO 101. Runs without lag.",
    "timestamp": "2026-08-14T04:02:47.464Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-14T04:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_jn80w_0",
    "appId": "kc3u0sl2h",
    "appSlug": "ever-777",
    "appName": "EVERY 77",
    "userName": "Deepak Singh",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on EVERY 77. Runs without lag.",
    "timestamp": "2026-08-22T02:02:47.464Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T02:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_qvsqk_1",
    "appId": "kc3u0sl2h",
    "appSlug": "ever-777",
    "appName": "EVERY 77",
    "userName": "Alok Verma",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-20T02:02:47.464Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T02:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_joi55_2",
    "appId": "kc3u0sl2h",
    "appSlug": "ever-777",
    "appName": "EVERY 77",
    "userName": "Pooja Reddy",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-18T02:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T02:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_ynrq0_3",
    "appId": "kc3u0sl2h",
    "appSlug": "ever-777",
    "appName": "EVERY 77",
    "userName": "Karan Mehta",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-16T02:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T02:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_6nscc_0",
    "appId": "v9ky6l07h",
    "appSlug": "love-rummy",
    "appName": "LOVE RUMMY",
    "userName": "Karan Mehta",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-22T01:02:47.464Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T01:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_melat_1",
    "appId": "v9ky6l07h",
    "appSlug": "love-rummy",
    "appName": "LOVE RUMMY",
    "userName": "Rohit Joshi",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-20T01:02:47.464Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T01:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_lzh0e_2",
    "appId": "v9ky6l07h",
    "appSlug": "love-rummy",
    "appName": "LOVE RUMMY",
    "userName": "Ananya Deshmukh",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-18T01:02:47.464Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T01:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_k2djz_3",
    "appId": "v9ky6l07h",
    "appSlug": "love-rummy",
    "appName": "LOVE RUMMY",
    "userName": "Suresh Raina",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-16T01:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T01:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_z0x61_4",
    "appId": "v9ky6l07h",
    "appSlug": "love-rummy",
    "appName": "LOVE RUMMY",
    "userName": "Priya Malik",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on LOVE RUMMY. Runs without lag.",
    "timestamp": "2026-08-14T01:02:47.464Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-14T01:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_2yon1_0",
    "appId": "0jfvh7lrx",
    "appSlug": "share-slots",
    "appName": "SHARE SLOTS",
    "userName": "Suresh Raina",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-22T00:02:47.464Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-22T00:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_8al4o_1",
    "appId": "0jfvh7lrx",
    "appSlug": "share-slots",
    "appName": "SHARE SLOTS",
    "userName": "Priya Malik",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-20T00:02:47.464Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-20T00:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_t915z_2",
    "appId": "0jfvh7lrx",
    "appSlug": "share-slots",
    "appName": "SHARE SLOTS",
    "userName": "Vikas Gupta",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on SHARE SLOTS. Runs without lag.",
    "timestamp": "2026-08-18T00:02:47.464Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-18T00:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_49jp6_3",
    "appId": "0jfvh7lrx",
    "appSlug": "share-slots",
    "appName": "SHARE SLOTS",
    "userName": "Vikram Sharma",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-16T00:02:47.464Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-16T00:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_1g0qt_4",
    "appId": "0jfvh7lrx",
    "appSlug": "share-slots",
    "appName": "SHARE SLOTS",
    "userName": "Rahul Verma",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-14T00:02:47.464Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-14T00:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_10k72_5",
    "appId": "0jfvh7lrx",
    "appSlug": "share-slots",
    "appName": "SHARE SLOTS",
    "userName": "Amit Patel",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-12T00:02:47.464Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-12T00:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_ez6jo_0",
    "appId": "89d79z398",
    "appSlug": "yono-vip",
    "appName": "YONO VIP",
    "userName": "Vikram Sharma",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on YONO VIP. Runs without lag.",
    "timestamp": "2026-08-21T23:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T23:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_ja2y6_1",
    "appId": "89d79z398",
    "appSlug": "yono-vip",
    "appName": "YONO VIP",
    "userName": "Rahul Verma",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-19T23:02:47.464Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T23:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_393q1_2",
    "appId": "89d79z398",
    "appSlug": "yono-vip",
    "appName": "YONO VIP",
    "userName": "Amit Patel",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-17T23:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T23:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_5iw6p_3",
    "appId": "89d79z398",
    "appSlug": "yono-vip",
    "appName": "YONO VIP",
    "userName": "Sneha Gamer",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-15T23:02:47.464Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T23:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_te0b1_0",
    "appId": "m6bwb6cnb",
    "appSlug": "maha-games",
    "appName": "MAHA GAMES",
    "userName": "Sneha Gamer",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-21T22:02:47.464Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T22:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_digi6_1",
    "appId": "m6bwb6cnb",
    "appSlug": "maha-games",
    "appName": "MAHA GAMES",
    "userName": "Dinesh Pro",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-19T22:02:47.464Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T22:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_mf77d_2",
    "appId": "m6bwb6cnb",
    "appSlug": "maha-games",
    "appName": "MAHA GAMES",
    "userName": "Kunal Roy",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-17T22:02:47.464Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T22:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_kumty_3",
    "appId": "m6bwb6cnb",
    "appSlug": "maha-games",
    "appName": "MAHA GAMES",
    "userName": "Deepak Singh",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-15T22:02:47.464Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T22:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_4stv5_4",
    "appId": "m6bwb6cnb",
    "appSlug": "maha-games",
    "appName": "MAHA GAMES",
    "userName": "Alok Verma",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on MAHA GAMES. Runs without lag.",
    "timestamp": "2026-08-13T22:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-13T22:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_3esh8_0",
    "appId": "y7lefyq14",
    "appSlug": "rummy-ludo",
    "appName": "RUMMY LUDO",
    "userName": "Deepak Singh",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-21T21:02:47.464Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T21:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_2iwxy_1",
    "appId": "y7lefyq14",
    "appSlug": "rummy-ludo",
    "appName": "RUMMY LUDO",
    "userName": "Alok Verma",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-19T21:02:47.464Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T21:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_3uy1g_2",
    "appId": "y7lefyq14",
    "appSlug": "rummy-ludo",
    "appName": "RUMMY LUDO",
    "userName": "Pooja Reddy",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on RUMMY LUDO. Runs without lag.",
    "timestamp": "2026-08-17T21:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T21:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_4qcp6_3",
    "appId": "y7lefyq14",
    "appSlug": "rummy-ludo",
    "appName": "RUMMY LUDO",
    "userName": "Karan Mehta",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-15T21:02:47.464Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T21:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_hbgr1_4",
    "appId": "y7lefyq14",
    "appSlug": "rummy-ludo",
    "appName": "RUMMY LUDO",
    "userName": "Rohit Joshi",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-13T21:02:47.464Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-13T21:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_8qy1x_5",
    "appId": "y7lefyq14",
    "appSlug": "rummy-ludo",
    "appName": "RUMMY LUDO",
    "userName": "Ananya Deshmukh",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-11T21:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-11T21:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_2kkg2_0",
    "appId": "lzcn7ehst",
    "appSlug": "789-jackports",
    "appName": "789 JACKPORTS",
    "userName": "Karan Mehta",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on 789 JACKPORTS. Runs without lag.",
    "timestamp": "2026-08-21T20:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T20:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_m8eto_1",
    "appId": "lzcn7ehst",
    "appSlug": "789-jackports",
    "appName": "789 JACKPORTS",
    "userName": "Rohit Joshi",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-19T20:02:47.464Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T20:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_8rp6i_2",
    "appId": "lzcn7ehst",
    "appSlug": "789-jackports",
    "appName": "789 JACKPORTS",
    "userName": "Ananya Deshmukh",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-17T20:02:47.464Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T20:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_yj3ke_3",
    "appId": "lzcn7ehst",
    "appSlug": "789-jackports",
    "appName": "789 JACKPORTS",
    "userName": "Suresh Raina",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-15T20:02:47.464Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T20:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_wytlx_0",
    "appId": "jl9bx9llw",
    "appSlug": "777-game",
    "appName": "777 GAME",
    "userName": "Suresh Raina",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-21T19:02:47.464Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T19:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_mofbm_1",
    "appId": "jl9bx9llw",
    "appSlug": "777-game",
    "appName": "777 GAME",
    "userName": "Priya Malik",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-19T19:02:47.464Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T19:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_364h9_2",
    "appId": "jl9bx9llw",
    "appSlug": "777-game",
    "appName": "777 GAME",
    "userName": "Vikas Gupta",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-17T19:02:47.464Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T19:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_cjb44_3",
    "appId": "jl9bx9llw",
    "appSlug": "777-game",
    "appName": "777 GAME",
    "userName": "Vikram Sharma",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-15T19:02:47.464Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T19:02:47.464Z"
  },
  {
    "id": "rev_1787407367464_ai9vu_4",
    "appId": "jl9bx9llw",
    "appSlug": "777-game",
    "appName": "777 GAME",
    "userName": "Rahul Verma",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on 777 GAME. Runs without lag.",
    "timestamp": "2026-08-13T19:02:47.464Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-13T19:02:47.464Z"
  },
  {
    "id": "rev_1787407367466_3bp1k_0",
    "appId": "dttfvdp67",
    "appSlug": "baccarist",
    "appName": "BACCARIST",
    "userName": "Vikram Sharma",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-21T18:02:47.466Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T18:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_8b1gg_1",
    "appId": "dttfvdp67",
    "appSlug": "baccarist",
    "appName": "BACCARIST",
    "userName": "Rahul Verma",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-19T18:02:47.466Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T18:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_dmdje_2",
    "appId": "dttfvdp67",
    "appSlug": "baccarist",
    "appName": "BACCARIST",
    "userName": "Amit Patel",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on BACCARIST. Runs without lag.",
    "timestamp": "2026-08-17T18:02:47.466Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T18:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_r1uha_3",
    "appId": "dttfvdp67",
    "appSlug": "baccarist",
    "appName": "BACCARIST",
    "userName": "Sneha Gamer",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-15T18:02:47.466Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T18:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_1ek58_4",
    "appId": "dttfvdp67",
    "appSlug": "baccarist",
    "appName": "BACCARIST",
    "userName": "Dinesh Pro",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-13T18:02:47.466Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-13T18:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_f918o_5",
    "appId": "dttfvdp67",
    "appSlug": "baccarist",
    "appName": "BACCARIST",
    "userName": "Kunal Roy",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-11T18:02:47.466Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-11T18:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_sdyb9_0",
    "appId": "3h5w608rt",
    "appSlug": "solitaire",
    "appName": "SOLITAIRE",
    "userName": "Sneha Gamer",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on SOLITAIRE. Runs without lag.",
    "timestamp": "2026-08-21T17:02:47.466Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T17:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_9lsvh_1",
    "appId": "3h5w608rt",
    "appSlug": "solitaire",
    "appName": "SOLITAIRE",
    "userName": "Dinesh Pro",
    "rating": 4,
    "reviewText": "Great graphics and clean table layout. Really enjoying the gameplay experience.",
    "timestamp": "2026-08-19T17:02:47.466Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T17:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_u7xy7_2",
    "appId": "3h5w608rt",
    "appSlug": "solitaire",
    "appName": "SOLITAIRE",
    "userName": "Kunal Roy",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-17T17:02:47.466Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T17:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_va00d_3",
    "appId": "3h5w608rt",
    "appSlug": "solitaire",
    "appName": "SOLITAIRE",
    "userName": "Deepak Singh",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-15T17:02:47.466Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T17:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_yx1mb_0",
    "appId": "ne1n96k01",
    "appSlug": "vita-mahjong",
    "appName": "VITA MAHJONG",
    "userName": "Deepak Singh",
    "rating": 5,
    "reviewText": "One of the best apps in this category. Lightweight and fast matchmaking.",
    "timestamp": "2026-08-21T16:02:47.466Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": true,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-21T16:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_psxf7_1",
    "appId": "ne1n96k01",
    "appSlug": "vita-mahjong",
    "appName": "VITA MAHJONG",
    "userName": "Alok Verma",
    "rating": 4,
    "reviewText": "Clean UI and easy to understand rules. Works nicely even on older Android phones.",
    "timestamp": "2026-08-19T16:02:47.466Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-19T16:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_2gpcp_2",
    "appId": "ne1n96k01",
    "appSlug": "vita-mahjong",
    "appName": "VITA MAHJONG",
    "userName": "Pooja Reddy",
    "rating": 5,
    "reviewText": "Really fun game mechanics and nice sound effects. 5 stars from my side!",
    "timestamp": "2026-08-17T16:02:47.466Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-17T16:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_wlilr_3",
    "appId": "ne1n96k01",
    "appSlug": "vita-mahjong",
    "appName": "VITA MAHJONG",
    "userName": "Karan Mehta",
    "rating": 4,
    "reviewText": "Solid performance and very stable connection. The lobby design is great.",
    "timestamp": "2026-08-15T16:02:47.466Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-15T16:02:47.466Z"
  },
  {
    "id": "rev_1787407367466_f6d2f_4",
    "appId": "ne1n96k01",
    "appSlug": "vita-mahjong",
    "appName": "VITA MAHJONG",
    "userName": "Rohit Joshi",
    "rating": 5,
    "reviewText": "Smooth interface and very responsive controls on VITA MAHJONG. Runs without lag.",
    "timestamp": "2026-08-13T16:02:47.466Z",
    "status": "published",
    "helpful_count": 8,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-08-13T16:02:47.466Z"
  }
];
