// Auto-generated verified community reviews dataset
export interface StaticReviewRecord {
  id: string;
  appId: string;
  appSlug?: string;
  appName?: string;
  userName: string;
  rating: number;
  reviewText: string;
  timestamp: string;
  status: "published" | "pending" | "rejected" | string;
  helpful_count: number;
  isPinned?: boolean;
  reported?: boolean;
  report_count?: number;
  source?: string;
  adminReply?: {
    text: string;
    author: string;
    timestamp: string;
  } | null;
  updated_at?: string;
}

export const STATIC_COMMUNITY_REVIEWS: StaticReviewRecord[] = [
  {
    "id": "_status_check_1789215801949",
    "appId": "",
    "appSlug": "",
    "appName": "",
    "userName": "Player",
    "rating": 5,
    "reviewText": "",
    "timestamp": "2026-09-13T13:33:22.051Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_rest_healthcheck",
    "adminReply": null,
    "updated_at": "2026-09-13T13:37:28.087Z"
  },
  {
    "id": "dgbPtTotZXpr900GSLKC",
    "appId": "spin-crush",
    "appSlug": "",
    "appName": "",
    "userName": "Player_Vikram",
    "rating": 5,
    "reviewText": "Really great app! Smooth working on my low cost smartphone",
    "timestamp": "2026-08-21T14:45:15.324Z",
    "status": "published",
    "helpful_count": 34,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "community",
    "adminReply": null,
    "updated_at": "2026-09-08T15:17:41.535Z"
  },
  {
    "id": "rev_08exxq5q9_device_1789723174978_527686fb",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "Amit_Tactician",
    "rating": 4,
    "reviewText": "Offline mode me bhi AI players solid challenge dete hain. Card animations are very fast, and sorting is seamless. Bas ek customized practice timer add ho jaye to tournament prep ke liye best offline app ban jayega.",
    "timestamp": "2026-09-18T09:19:34.978Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-18T09:19:34.978Z"
  },
  {
    "id": "rev_08exxq5q9_device_1789723176241_e82b0d3d",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "Kabir_RummyPro",
    "rating": 5,
    "reviewText": "The card drag-and-drop mechanics are incredibly responsive, and the auto-sort function arranges my hands instantly. Highly effective offline tool for practicing points calculations and defensive discards before tournaments.✅✅",
    "timestamp": "2026-09-18T09:19:36.241Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-18T09:19:36.241Z"
  },
  {
    "id": "rev_08exxq5q9_device_1789723178075_7902c786",
    "appId": "08exxq5q9",
    "appSlug": "abc-rummy",
    "appName": "ABC RUMMY",
    "userName": "RummyStrategist_99",
    "rating": 3,
    "reviewText": "The offline gameplay is smooth, but the discard pile touch target is slightly small, sometimes leading to accidental draws. Good for basic practice, but needs more precise controls for competitive speed.",
    "timestamp": "2026-09-18T09:19:38.075Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "ai_generated",
    "adminReply": null,
    "updated_at": "2026-09-18T09:19:38.075Z"
  },
  {
    "id": "rev_1787415289649_kvp9n",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "lokesh_m3958",
    "rating": 4,
    "reviewText": "nice gameplay, smooth 60fps",
    "timestamp": "2026-08-22T16:14:49.650Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:49.650Z"
  },
  {
    "id": "rev_1787415289969_4xu84",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "Mumbai_Don",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and The Table Experience is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:14:49.969Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:49.969Z"
  },
  {
    "id": "rev_1787415290295_n1kv8",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "Marathi_Manus53",
    "rating": 5,
    "reviewText": "Really like App Performance and the sound design. The visual clarity on RUMMY 77 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:14:50.295Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:50.295Z"
  },
  {
    "id": "rev_1787415290635_fr7lp",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "Thunder_Bolt74",
    "rating": 4,
    "reviewText": "enjoying the matches, Overview & Game Mechanics is great",
    "timestamp": "2026-08-22T16:14:50.635Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:50.635Z"
  },
  {
    "id": "rev_1787415291161_rz70v",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "Delhi_Bhai",
    "rating": 2,
    "reviewText": "The core game rules and Overview & Game Mechanics are good, but the app heats up my older phone a bit after 30 minutes of continuous play. Needs optimization.",
    "timestamp": "2026-08-22T16:14:51.161Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:51.161Z"
  },
  {
    "id": "rev_1787415291625_bt4uf",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "Gaming_Beast26",
    "rating": 5,
    "reviewText": "Really like App Performance and the sound design. The visual clarity on RUMMY 77 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:14:51.625Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:51.626Z"
  },
  {
    "id": "rev_1787415291950_xqpzw",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "Waseem_Akram",
    "rating": 5,
    "reviewText": "zero lag during matches, pure entertainment 🎮",
    "timestamp": "2026-08-22T16:14:51.950Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:51.950Z"
  },
  {
    "id": "rev_1787415292261_43i85",
    "appId": "i5uw2apum",
    "appSlug": "",
    "appName": "",
    "userName": "Smart_Boy75",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. The Table Experience runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:14:52.261Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:14:52.261Z"
  },
  {
    "id": "rev_1787415445888_8pzix",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "Desi_Girl36",
    "rating": 5,
    "reviewText": "mast game hai, ultra smooth animations 🔥",
    "timestamp": "2026-08-22T16:17:25.888Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:25.888Z"
  },
  {
    "id": "rev_1787415446203_h54wp",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "sneha_gamer3562",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and 1. Strategy & Skill Rooms (Classic Rummy) is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:17:26.203Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:26.203Z"
  },
  {
    "id": "rev_1787415446529_i0ujz",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "Mumbai_Don",
    "rating": 5,
    "reviewText": "Really like 2. The Social Lounge (Teen Patti & Card Classics) and the sound design. The visual clarity on RUMMY 91 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:17:26.529Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:26.529Z"
  },
  {
    "id": "rev_1787415446894_0bfvi",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "Tanmay_7",
    "rating": 4,
    "reviewText": "enjoying the matches, Inside Rummy 91: The Game Library is great",
    "timestamp": "2026-08-22T16:17:26.894Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:26.894Z"
  },
  {
    "id": "rev_1787415447234_nmq8d",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "gaming_beast5128",
    "rating": 4,
    "reviewText": "Great game with slick animations. Inside Rummy 91: The Game Library runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T16:17:27.234Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:27.234Z"
  },
  {
    "id": "rev_1787415447591_n7oqc",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "Rakesh_Dev99",
    "rating": 5,
    "reviewText": "Really like 2. The Social Lounge (Teen Patti & Card Classics) and the sound design. The visual clarity on RUMMY 91 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:17:27.591Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:27.591Z"
  },
  {
    "id": "rev_1787415448215_d9c7t",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "Faisal_A82",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and Inside Rummy 91: The Game Library is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T16:17:28.215Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:28.215Z"
  },
  {
    "id": "rev_1787415448548_pkhp6",
    "appId": "s4oc5m16b",
    "appSlug": "",
    "appName": "",
    "userName": "Suraj_Prasad",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. 1. Strategy & Skill Rooms (Classic Rummy) runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:17:28.548Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:17:28.548Z"
  },
  {
    "id": "rev_1787415505482_jowdf",
    "appId": "ha76icslh",
    "appSlug": "",
    "appName": "",
    "userName": "Ajay_Tech63",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and Overview is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T16:18:25.482Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:18:25.482Z"
  },
  {
    "id": "rev_1787415505839_f1n4b",
    "appId": "ha76icslh",
    "appSlug": "",
    "appName": "",
    "userName": "beta_tester2517",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and How the Game Plays is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:18:25.839Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:18:25.839Z"
  },
  {
    "id": "rev_1787415506165_afrx0",
    "appId": "ha76icslh",
    "appSlug": "",
    "appName": "",
    "userName": "Simran_Kaur22",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. Overview works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T16:18:26.165Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:18:26.165Z"
  },
  {
    "id": "rev_1787415506480_zt7wv",
    "appId": "ha76icslh",
    "appSlug": "",
    "appName": "",
    "userName": "SaurabhJ.47",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T16:18:26.480Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:18:26.480Z"
  },
  {
    "id": "rev_1787415506825_w0d2w",
    "appId": "ha76icslh",
    "appSlug": "",
    "appName": "",
    "userName": "bipin_r7612",
    "rating": 4,
    "reviewText": "Great game with slick animations. Overview runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T16:18:26.825Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:18:26.825Z"
  },
  {
    "id": "rev_1787415551617_f49om",
    "appId": "colrcaih7",
    "appSlug": "",
    "appName": "",
    "userName": "Anand_Play45",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. What the Application Provides runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:19:11.617Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:19:11.617Z"
  },
  {
    "id": "rev_1787415551945_3cixw",
    "appId": "colrcaih7",
    "appSlug": "",
    "appName": "",
    "userName": "imran_khan6321",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. About the Application (Deep Dive) works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T16:19:11.945Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:19:11.945Z"
  },
  {
    "id": "rev_1787415552245_4zx89",
    "appId": "colrcaih7",
    "appSlug": "",
    "appName": "",
    "userName": "Ranjan_B",
    "rating": 4,
    "reviewText": "enjoying the matches, About the Application (Deep Dive) is great",
    "timestamp": "2026-08-22T16:19:12.245Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:19:12.245Z"
  },
  {
    "id": "rev_1787415552597_mfmp2",
    "appId": "colrcaih7",
    "appSlug": "",
    "appName": "",
    "userName": "Cute_Munda",
    "rating": 3,
    "reviewText": "Decent game with good animations and What the Application Provides. Would be great if they optimized the battery usage a bit more during extended 2-hour sessions.",
    "timestamp": "2026-08-22T16:19:12.597Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:19:12.597Z"
  },
  {
    "id": "rev_1787415643945_t0zi2",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "Sameer_S55",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and Technical Architecture and Application Details is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T16:20:43.945Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:43.945Z"
  },
  {
    "id": "rev_1787415644449_mryrf",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "Lokesh_M27",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. System Specifications and Footprint runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:20:44.449Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:44.449Z"
  },
  {
    "id": "rev_1787415644930_pq51c",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "Bad_Boy",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. Technical Architecture and Application Details works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T16:20:44.930Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:44.930Z"
  },
  {
    "id": "rev_1787415645496_nkela",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "Tarun_Kumar41",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T16:20:45.496Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:45.496Z"
  },
  {
    "id": "rev_1787415645882_sueut",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "manoj_kumar1574",
    "rating": 2,
    "reviewText": "The core game rules and Technical Architecture and Application Details are good, but the app heats up my older phone a bit after 30 minutes of continuous play. Needs optimization.",
    "timestamp": "2026-08-22T16:20:45.882Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:45.882Z"
  },
  {
    "id": "rev_1787415646196_2k3cw",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "Dark_Knight47",
    "rating": 5,
    "reviewText": "Really like Monetization Framework and App Economy and the sound design. The visual clarity on JOY RUMMY makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:20:46.196Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:46.196Z"
  },
  {
    "id": "rev_1787415646743_qw5dg",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "abhishek_dubey218",
    "rating": 5,
    "reviewText": "zero lag during matches, pure entertainment 🎮",
    "timestamp": "2026-08-22T16:20:46.743Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:46.743Z"
  },
  {
    "id": "rev_1787415647124_d2j1d",
    "appId": "e1qcs5ik7",
    "appSlug": "",
    "appName": "",
    "userName": "Arun Varma",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. System Specifications and Footprint runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:20:47.124Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:20:47.124Z"
  },
  {
    "id": "rev_1787415691536_p5cz8",
    "appId": "to56xasfo",
    "appSlug": "",
    "appName": "",
    "userName": "ravi_shankar2832",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and Core Game Mechanics is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:21:31.536Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:21:31.536Z"
  },
  {
    "id": "rev_1787415691914_8bmix",
    "appId": "to56xasfo",
    "appSlug": "",
    "appName": "",
    "userName": "Yogesh_Gaming",
    "rating": 5,
    "reviewText": "Really like Engaging Play Modes and Accessibility and the sound design. The visual clarity on JAIHO 91 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:21:31.914Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:21:31.914Z"
  },
  {
    "id": "rev_1787415692253_41y99",
    "appId": "to56xasfo",
    "appSlug": "",
    "appName": "",
    "userName": "Kritika_M",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T16:21:32.253Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:21:32.253Z"
  },
  {
    "id": "rev_1787415692600_l4zqa",
    "appId": "to56xasfo",
    "appSlug": "",
    "appName": "",
    "userName": "tushar_gamer7531",
    "rating": 5,
    "reviewText": "Clean table design and easy card grouping. Everything feels responsive and polished.",
    "timestamp": "2026-08-22T16:21:32.600Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:21:32.600Z"
  },
  {
    "id": "rev_1787415693039_hjta4",
    "appId": "to56xasfo",
    "appSlug": "",
    "appName": "",
    "userName": "Alok Verma",
    "rating": 5,
    "reviewText": "Really like Engaging Play Modes and Accessibility and the sound design. The visual clarity on JAIHO 91 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:21:33.039Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:21:33.039Z"
  },
  {
    "id": "rev_1787415693750_8zpuy",
    "appId": "to56xasfo",
    "appSlug": "",
    "appName": "",
    "userName": "Lokesh_M76",
    "rating": 4,
    "reviewText": "good game, pls add more custom themes 👍",
    "timestamp": "2026-08-22T16:21:33.750Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:21:33.750Z"
  },
  {
    "id": "rev_1787415694398_34ops",
    "appId": "to56xasfo",
    "appSlug": "",
    "appName": "",
    "userName": "ashish_t7818",
    "rating": 4,
    "reviewText": "Very well made app with Engaging Play Modes and Accessibility. Quick match finding and nice animations. 4 stars, just waiting for the next feature update!",
    "timestamp": "2026-08-22T16:21:34.398Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:21:34.398Z"
  },
  {
    "id": "rev_1787415722886_osz07",
    "appId": "x1mivt2cj",
    "appSlug": "",
    "appName": "",
    "userName": "Ritwik Sengupta",
    "rating": 5,
    "reviewText": "Finally a card game that works like a proper logic puzzle. Love clearing the board layout by making valid runs and sets instead of rushing against a timer. The soft background music makes it super relaxing after office work. Great concept!",
    "timestamp": "2026-08-22T16:22:02.886Z",
    "status": "published",
    "helpful_count": 14,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:22:02.886Z"
  },
  {
    "id": "rev_1787415723192_mkcn5",
    "appId": "x1mivt2cj",
    "appSlug": "",
    "appName": "",
    "userName": "Harsh_Vardhan88",
    "rating": 3,
    "reviewText": "Concept accha hai puzzle wala but later thematic zones on the map are very tough. Limited draw pile bohot jaldi khatam ho jati hai and trapped cards unlock nahi hote. Limited undo buttons are not enough for hard stages, please give more hints or balance the draw deck.",
    "timestamp": "2026-08-22T16:22:03.192Z",
    "status": "published",
    "helpful_count": 9,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:22:03.192Z"
  },
  {
    "id": "rev_1787415723546_j1bnh",
    "appId": "x1mivt2cj",
    "appSlug": "",
    "appName": "",
    "userName": "Sneha Kulkarni",
    "rating": 4,
    "reviewText": "Very good for brain training. You really have to plan 3-4 moves ahead before drawing cards so you don't get stuck. Drag and tap controls are buttery smooth on my phone. Unlocked 3 zones so far with 3 stars each. 👍",
    "timestamp": "2026-08-22T16:22:03.546Z",
    "status": "published",
    "helpful_count": 11,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:22:03.546Z"
  },
  {
    "id": "rev_1787415723870_abs5j",
    "appId": "x1mivt2cj",
    "appSlug": "",
    "appName": "",
    "userName": "devraj_solanki",
    "rating": 5,
    "reviewText": "Best part is there is no annoying match timer! Poora focus board clear karne aur virtual stars collect karne pe rehta hai. The visual themes change nicely as you move forward on the map. Bahut clean interface hai.",
    "timestamp": "2026-08-22T16:22:03.870Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:22:03.870Z"
  },
  {
    "id": "rev_1787415724229_kh4hr",
    "appId": "x1mivt2cj",
    "appSlug": "",
    "appName": "",
    "userName": "Jithin Mathew",
    "rating": 4,
    "reviewText": "Interesting take on classic matching rules. Managing the draw pile at the bottom needs real strategy or you run out of moves. The hint system helped me figure out how to expose hidden face-down cards a couple of times. Solid casual game.",
    "timestamp": "2026-08-22T16:22:04.229Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:22:04.229Z"
  },
  {
    "id": "rev_1787415794723_c1lhr",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Gaurav Das",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and The Core Game Mechanics is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:23:14.723Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:14.723Z"
  },
  {
    "id": "rev_1787415795039_rvkhy",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "sumit_bhai6269",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on JAIHO SLOTS makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:15.039Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:15.039Z"
  },
  {
    "id": "rev_1787415795387_2jsgh",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Angel_Priya",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T16:23:15.387Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:15.387Z"
  },
  {
    "id": "rev_1787415795703_u1qx0",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "nitin_s5893",
    "rating": 4,
    "reviewText": "Great game with slick animations. Part 1: Key Features and Core Mechanics of Jaiho Slots runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T16:23:15.703Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:15.703Z"
  },
  {
    "id": "rev_1787415796040_m638g",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "ritu_sharma6279",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on JAIHO SLOTS makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:16.040Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:16.040Z"
  },
  {
    "id": "rev_1787415796420_i64tq",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Zaid_Khan17",
    "rating": 5,
    "reviewText": "zero lag during matches, pure entertainment 🎮",
    "timestamp": "2026-08-22T16:23:16.420Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:16.420Z"
  },
  {
    "id": "rev_1787415796762_38l9t",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Mumbai_Don",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. The Core Game Mechanics runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:23:16.762Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:16.762Z"
  },
  {
    "id": "rev_1787415797135_v2pmb",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Neha_S",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on JAIHO SLOTS makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:17.135Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:17.135Z"
  },
  {
    "id": "rev_1787415797553_scly2",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Arif_M36",
    "rating": 5,
    "reviewText": "great update, Part 1: Key Features and Core Mechanics of Jaiho Slots works flawlessly!",
    "timestamp": "2026-08-22T16:23:17.553Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:17.553Z"
  },
  {
    "id": "rev_1787415797882_pkvgs",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Ramesh_G",
    "rating": 5,
    "reviewText": "Clean table design and easy card grouping. Everything feels responsive and polished.",
    "timestamp": "2026-08-22T16:23:17.882Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:17.882Z"
  },
  {
    "id": "rev_1787415798282_8n4e0",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Vijay_Kumar",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on JAIHO SLOTS makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:18.282Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:18.282Z"
  },
  {
    "id": "rev_1787415798825_nkmai",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Akash_Deep",
    "rating": 5,
    "reviewText": "best card app for daily timepass",
    "timestamp": "2026-08-22T16:23:18.825Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:18.825Z"
  },
  {
    "id": "rev_1787415799171_7bmev",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "South_Indian_Gamer",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. The Core Game Mechanics runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:23:19.171Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:19.171Z"
  },
  {
    "id": "rev_1787415799486_ulgp3",
    "appId": "ozhj4pz5s",
    "appSlug": "",
    "appName": "",
    "userName": "Tariq_Ahmed",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on JAIHO SLOTS makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:19.486Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:19.486Z"
  },
  {
    "id": "rev_1787415823738_id4t7",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Faisal_A",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and Key Features and Core Mechanics of Yono Arcade is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T16:23:43.738Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:43.738Z"
  },
  {
    "id": "rev_1787415824058_4wjaj",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "SaurabhJ.34",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and The Core Game Mechanics is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:23:44.058Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:44.058Z"
  },
  {
    "id": "rev_1787415824374_8302a",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "KaranMehta26",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on YONO ARCADE makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:44.374Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:44.374Z"
  },
  {
    "id": "rev_1787415824813_nq80d",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Rahul Sharma",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T16:23:44.813Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:44.813Z"
  },
  {
    "id": "rev_1787415825598_wxi7d",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Kunal Roy",
    "rating": 4,
    "reviewText": "Great game with slick animations. Key Features and Core Mechanics of Yono Arcade runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T16:23:45.598Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:45.598Z"
  },
  {
    "id": "rev_1787415826018_9yqn6",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Dinesh_Pro93",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on YONO ARCADE makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:46.018Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:46.018Z"
  },
  {
    "id": "rev_1787415826330_quwxs",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Sameer_S",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and Key Features and Core Mechanics of Yono Arcade is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T16:23:46.330Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:46.330Z"
  },
  {
    "id": "rev_1787415826632_ckfl2",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Prashant_K34",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. The Core Game Mechanics runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:23:46.632Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:46.632Z"
  },
  {
    "id": "rev_1787415826956_0zl2e",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Crazy_Gamer",
    "rating": 4,
    "reviewText": "Great game with slick animations. Key Features and Core Mechanics of Yono Arcade runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T16:23:46.956Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:46.956Z"
  },
  {
    "id": "rev_1787415827284_8xjkv",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Thunder_Bolt",
    "rating": 5,
    "reviewText": "great update, Key Features and Core Mechanics of Yono Arcade works flawlessly!",
    "timestamp": "2026-08-22T16:23:47.284Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:47.284Z"
  },
  {
    "id": "rev_1787415827611_qh13k",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Beta_Tester",
    "rating": 5,
    "reviewText": "The tournament lobby mode is super engaging. Love the competitive leaderboard system and The Core Game Mechanics!",
    "timestamp": "2026-08-22T16:23:47.611Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:47.611Z"
  },
  {
    "id": "rev_1787415827920_l1vct",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "rakesh_dev5957",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on YONO ARCADE makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:23:47.920Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:47.920Z"
  },
  {
    "id": "rev_1787415828239_y3fyy",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Sneha_Gamer",
    "rating": 4,
    "reviewText": "very responsive UI and clean design",
    "timestamp": "2026-08-22T16:23:48.239Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:48.239Z"
  },
  {
    "id": "rev_1787415828564_1pn5z",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Yogesh_Gaming",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. The Core Game Mechanics runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:23:48.564Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:48.564Z"
  },
  {
    "id": "rev_1787415828884_nf2jl",
    "appId": "l7e8oyo9m",
    "appSlug": "",
    "appName": "",
    "userName": "Abhishek Dubey",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. Key Features and Core Mechanics of Yono Arcade works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T16:23:48.884Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:23:48.884Z"
  },
  {
    "id": "rev_1787415869699_xn2bk",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "vikas_verma5548",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and The Core Game Mechanics is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:24:29.699Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:29.699Z"
  },
  {
    "id": "rev_1787415870046_fugrs",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Salman_K19",
    "rating": 5,
    "reviewText": "Really like Educational and Strategic Value and the sound design. The visual clarity on BINGO 101 makes long sessions easy on the eyes. Top tier development!",
    "timestamp": "2026-08-22T16:24:30.046Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:30.046Z"
  },
  {
    "id": "rev_1787415870387_pmcb8",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Beta_Tester48",
    "rating": 5,
    "reviewText": "love the table visual effects! 🤩",
    "timestamp": "2026-08-22T16:24:30.387Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:30.387Z"
  },
  {
    "id": "rev_1787415870710_2vb16",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Lokesh_M",
    "rating": 3,
    "reviewText": "Decent game with good animations and The Core Game Mechanics. Would be great if they optimized the battery usage a bit more during extended 2-hour sessions.",
    "timestamp": "2026-08-22T16:24:30.710Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:30.710Z"
  },
  {
    "id": "rev_1787415871121_0zu4b",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Sumit_Bhai",
    "rating": 3,
    "reviewText": "Good concept and responsive touch controls. The in-game guide for Part 1: Key Features and Core Mechanics of Bingo 101 could be a bit more detailed for new players.",
    "timestamp": "2026-08-22T16:24:31.121Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:31.121Z"
  },
  {
    "id": "rev_1787415871469_jsstn",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Imran_Khan96",
    "rating": 4,
    "reviewText": "good game, pls add more custom themes 👍",
    "timestamp": "2026-08-22T16:24:31.469Z",
    "status": "published",
    "helpful_count": 6,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:31.469Z"
  },
  {
    "id": "rev_1787415872382_o048q",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "ajay_tech2381",
    "rating": 3,
    "reviewText": "Decent game with good animations and The Core Game Mechanics. Would be great if they optimized the battery usage a bit more during extended 2-hour sessions.",
    "timestamp": "2026-08-22T16:24:32.382Z",
    "status": "published",
    "helpful_count": 2,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:32.382Z"
  },
  {
    "id": "rev_1787415872722_yzus5",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Marathi_Manus75",
    "rating": 4,
    "reviewText": "Great game with slick animations. Part 1: Key Features and Core Mechanics of Bingo 101 runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T16:24:32.722Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:32.722Z"
  },
  {
    "id": "rev_1787415873054_cvwti",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "SanjayRajput58",
    "rating": 2,
    "reviewText": "Graphics are nice, but font sizes on smaller screens feel a bit cramped. Hope the developers refine Educational and Strategic Value in the next patch.",
    "timestamp": "2026-08-22T16:24:33.054Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:33.054Z"
  },
  {
    "id": "rev_1787415873368_et2n5",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Alpha_Male17",
    "rating": 5,
    "reviewText": "Clean table design and easy card grouping. Everything feels responsive and polished.",
    "timestamp": "2026-08-22T16:24:33.368Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:33.368Z"
  },
  {
    "id": "rev_1787415873869_s1eeg",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Waseem_Akram23",
    "rating": 3,
    "reviewText": "Good concept and responsive touch controls. The in-game guide for Part 1: Key Features and Core Mechanics of Bingo 101 could be a bit more detailed for new players.",
    "timestamp": "2026-08-22T16:24:33.869Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:33.869Z"
  },
  {
    "id": "rev_1787415874348_oy2tk",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Waseem_Akram81",
    "rating": 5,
    "reviewText": "best card app for daily timepass",
    "timestamp": "2026-08-22T16:24:34.348Z",
    "status": "published",
    "helpful_count": 4,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:34.348Z"
  },
  {
    "id": "rev_1787415874867_fh3vc",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "bipin_r5137",
    "rating": 5,
    "reviewText": "One of the most optimized apps in this genre. The Core Game Mechanics runs without any stuttering. Great battery efficiency and intuitive interface. 5 stars! 👍",
    "timestamp": "2026-08-22T16:24:34.867Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:34.867Z"
  },
  {
    "id": "rev_1787415875300_qxmre",
    "appId": "jr5xf2b1s",
    "appSlug": "",
    "appName": "",
    "userName": "Karan Mehta",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. Part 1: Key Features and Core Mechanics of Bingo 101 works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T16:24:35.300Z",
    "status": "published",
    "helpful_count": 1,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:24:35.300Z"
  },
  {
    "id": "rev_1787415928950_8msqn",
    "appId": "08exxq5q9",
    "appSlug": "",
    "appName": "",
    "userName": "Riya_Gupta",
    "rating": 3,
    "reviewText": "Gameplay mechanics are fun and Part 1: Key Features and Core Mechanics of ABC Rummy is great, but takes a few seconds longer to connect on weak mobile data. Works great on Wi-Fi though.",
    "timestamp": "2026-08-22T16:25:28.950Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:25:28.950Z"
  },
  {
    "id": "rev_1787415929290_wt88k",
    "appId": "08exxq5q9",
    "appSlug": "",
    "appName": "",
    "userName": "Punjabi_Munda",
    "rating": 3,
    "reviewText": "Decent game with good animations and The Core Game Mechanics. Would be great if they optimized the battery usage a bit more during extended 2-hour sessions.",
    "timestamp": "2026-08-22T16:25:29.290Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:25:29.290Z"
  },
  {
    "id": "rev_1787415929635_6yulu",
    "appId": "08exxq5q9",
    "appSlug": "",
    "appName": "",
    "userName": "Prashant_K72",
    "rating": 4,
    "reviewText": "Really fun mechanics and nice sound effects. Part 1: Key Features and Core Mechanics of ABC Rummy works great. Only minor request is to make the card numbers slightly larger on compact screens. 👌",
    "timestamp": "2026-08-22T16:25:29.635Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:25:29.635Z"
  },
  {
    "id": "rev_1787415929964_rlnfv",
    "appId": "08exxq5q9",
    "appSlug": "",
    "appName": "",
    "userName": "Salman_K90",
    "rating": 4,
    "reviewText": "enjoying the matches, Part 1: Key Features and Core Mechanics of ABC Rummy is great",
    "timestamp": "2026-08-22T16:25:29.964Z",
    "status": "published",
    "helpful_count": 3,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:25:29.964Z"
  },
  {
    "id": "rev_1787415930319_y8g84",
    "appId": "08exxq5q9",
    "appSlug": "",
    "appName": "",
    "userName": "SanjayRajput25",
    "rating": 4,
    "reviewText": "Great game with slick animations. Part 1: Key Features and Core Mechanics of ABC Rummy runs super smooth on my phone. Would love to see more custom table themes in the next update!",
    "timestamp": "2026-08-22T16:25:30.319Z",
    "status": "published",
    "helpful_count": 7,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:25:30.319Z"
  },
  {
    "id": "rev_1787415930660_g4muz",
    "appId": "08exxq5q9",
    "appSlug": "",
    "appName": "",
    "userName": "Mortal_Soul48",
    "rating": 4,
    "reviewText": "Solid gameplay and very stable connection. The UI is straightforward and The Core Game Mechanics is well designed. A custom card back option would make it even better.",
    "timestamp": "2026-08-22T16:25:30.660Z",
    "status": "published",
    "helpful_count": 0,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:25:30.660Z"
  },
  {
    "id": "rev_1787415930987_509if",
    "appId": "08exxq5q9",
    "appSlug": "",
    "appName": "",
    "userName": "Viper_X",
    "rating": 5,
    "reviewText": "zero lag during matches, pure entertainment 🎮",
    "timestamp": "2026-08-22T16:25:30.987Z",
    "status": "published",
    "helpful_count": 5,
    "isPinned": false,
    "reported": false,
    "report_count": 0,
    "source": "admin_created",
    "adminReply": null,
    "updated_at": "2026-08-22T16:25:30.987Z"
  }
];
