import fs from 'fs';
let content = fs.readFileSync('src/lib/communityFirebase.ts', 'utf8');

const targetStr = "} catch (queryErr) {\n          // Query fallback failed\n        }";
const newStr = "} catch (queryErr) {\n          // Query fallback failed\n        }\n      }\n    }\n\n    if (allLoadedReviews.length > 0) {\n      allLoadedReviews.sort((a, b) => new Date(b.created_at || 0).getTime() - new Date(a.created_at || 0).getTime());\n      const enriched = attachLocalUserReviews(allLoadedReviews);\n      const result: ReviewFetchResult = { reviews: enriched, hasMore: false, nextCursor: null, stats: loadedStats };\n      if (!cursor && filter === 'all' && sortBy === 'recent') targets.forEach(t => setCachedLiveReviews(t, result));\n      return result;\n    }\n  } catch (err) {\n    console.warn('[fetchLiveReviews] Direct REST fallback failed:', err);\n  }\n\n  // 3. Final Fallback: Static Data\n  try {\n    const { STATIC_COMMUNITY_REVIEWS } = require('./communityStoreFallback');\n    if (STATIC_COMMUNITY_REVIEWS && STATIC_COMMUNITY_REVIEWS.length > 0) {\n      const fallbacks = STATIC_COMMUNITY_REVIEWS.filter((r: any) => \n        r.appId === targetId || r.appSlug === targetSlug || r.appId === targetSlug\n      ).map((r: any) => ({\n        id: r.id,\n        app_id: r.appId,\n        appId: r.appId,\n        appSlug: r.appSlug,\n        username: r.userName || 'Player',\n        rating: Number(r.rating) || 5,\n        comment: r.reviewText || '',\n        created_at: r.timestamp || new Date().toISOString(),\n        helpful_count: Number(r.helpful_count) || 0,\n        reported: Boolean(r.reported),\n        report_count: Number(r.report_count) || 0,\n        source: r.source || 'community',\n        isPinned: Boolean(r.isPinned),\n        adminReply: r.adminReply || null\n      }));\n      \n      if (fallbacks.length > 0) {\n        fallbacks.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());\n        const enriched = attachLocalUserReviews(fallbacks);\n        const result = { reviews: enriched, hasMore: false, nextCursor: null };\n        if (!cursor && filter === 'all' && sortBy === 'recent') targets.forEach(t => setCachedLiveReviews(t, result));\n        return result;\n      }\n    }\n  } catch(e) {}\n\n  const emptyResult = attachLocalUserReviews([]);\n  return { reviews: emptyResult, hasMore: false, nextCursor: null };\n}";

const oldReturnStr = "    if (allLoadedReviews.length > 0) {\n      // Sort and process results...\n      // (This assumes allLoadedReviews handles the rest of the block)\n";

// Actually, I should just use string replacement on a larger chunk
